"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character"""

right_format = """$cmd_duration $time"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[gcloud]
disabled = true

[time]
format = "[$time]($style)"
time_format = "%R"
style = "blue dimmed"
disabled = false

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[cmd_duration]
format = "[$duration]($style)"
min_time = 0
show_milliseconds = true
style = "yellow dimmed"
