"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character
"""

right_format = """
$cmd_duration\
$c\
$cmake\
$golang\
$java\
$kotlin\
$lua\
$nodejs\
$ocaml\
$php\
$python\
$rust\
$zig\
$helm\
$terraform\
$bun\
$time
"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[directory]
style = "bold purple"

[gcloud]
disabled = true

[time]
disabled = false
format = "[$time]($style)"
time_format = "%T"
style = "purple dimmed"

[git_branch]
symbol = ""
format = "[$symbol $branch(:$remote_branch)]($style) "
style = "bold cyan"

[cmd_duration]
format = "[$duration]($style) "
min_time = 0
show_milliseconds = true
style = "yellow dimmed"

[c]
symbol = " "
format = "[$symbol]($style)"
style = "dimmed"

[cmake]
symbol = " "
format = "[$symbol]($style)"
style = "dimmed"

[golang]
symbol = " "
format = "[$symbol]($style)"
style = "dimmed"

[java]
symbol = " "
format = "[$symbol]($style)"
style = "dimmed"

[kotlin]
symbol = " "
format = "[$symbol]($style)"
style = "dimmed"

[lua]
symbol = " "
format = "[$symbol]($style)"
style = "dimmed"

[nodejs]
symbol = " "
format = "[$symbol]($style)"
style = "dimmed"

[ocaml]
symbol = " "
format = "[$symbol]($style)"
style = "dimmed"

[php]
symbol = " "
format = "[$symbol]($style)"
style = "dimmed"

[python]
symbol = " "
format = "[$symbol]($style)"
style = "dimmed"

[rust]
symbol = " "
format = "[$symbol]($style)"
style = "dimmed"

[bun]
symbol = " "
format = "[$symbol]($style)"
style = "dimmed"

[zig]
symbol = " "
format = "[$symbol]($style)"
style = "dimmed"

[helm]
symbol = "⎈ "
format = "[$symbol]($style)"
style = "dimmed"

[terraform]
symbol = " "
format = "[$symbol]($style)"
style = "dimmed"

